<?php
// tests/AuthenticationTest.php

namespace App\Tests\auth;

use ApiPlatform\Symfony\Bundle\Test\ApiTestCase;
use App\Entity\ApiUser;
use Hautelook\AliceBundle\PhpUnit\ReloadDatabaseTrait;

class AuthenticationTest extends ApiTestCase
{
    use ReloadDatabaseTrait;

    public function testLogin(): void
    {

        $client = self::createClient();
        $container = self::getContainer();

        $password = '$3CR3T';
        $user = new ApiUser();
        $user->setEmail('test@apitest.com');
        $user->setPassword(
            $container->get('security.user_password_hasher')->hashPassword($user, $password)
        );
        $roles = $user->getRoles();
        $roles[] = 'ROLE_ADMIN';
        $user->setRoles($roles);
        $manager = $container->get('doctrine')->getManager();
        $manager->persist($user);
        $manager->flush();

        $apiUrl = 'https://localhost:8000';
        // retrieve a token
        $response = $client->request('POST', "{$apiUrl}/auth", [
            'headers' => ['Content-Type' => 'application/json'],
            'json' => [
                'email' => $user->getEmail(),
                'password' => $password,
            ],
        ]);

        $json = $response->toArray();
        $this->assertResponseIsSuccessful();
        $this->assertArrayHasKey('token', $json);
        $path = "$apiUrl/api_users";
        // test not authorized
        $client->request('GET', $path, ['headers' => ['Accept' => 'application/json', 'Content-Type' => 'application/json']]);
        $this->assertResponseStatusCodeSame(401);

        // test authorized
        $response = $client->request('GET', $path, [
            'auth_bearer' => $json['token'],
            'headers' => [
                'Accept' => 'application/json',
                'Content-Type' => 'application/json'
            ]]);
        $this->assertResponseIsSuccessful();
        $users = $response->toArray();
        $this->assertIsArray($users);
        $result = array_find($users, function (array $value) use ($user) {
            return $value['email'] === $user->getEmail();
        });
        $this->assertIsArray($result);
        $this->assertEquals($user->getEmail(), $result['email']);

        $path = "$apiUrl/auth-refresh";

        $response = $client->request('GET', $path, [
            'auth_bearer' => $json['token'],
            'headers' => [
                'Accept' => 'application/json',
                'Content-Type' => 'application/json'
            ]]);
        $this->assertResponseIsSuccessful();
        $json = $response->toArray();

        $response = $client->request('GET', $path, [
            'auth_bearer' => $json['token'],
            'headers' => [
                'Accept' => 'application/json',
                'Content-Type' => 'application/json'
            ]]);
        $this->assertResponseIsSuccessful();


    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        self::$alwaysBootKernel = false;
    }
}