<?php

namespace App\Tests\Controller;

use ApiPlatform\Symfony\Bundle\Test\ApiTestCase;
use App\DTO\SetupDTO;
use Hautelook\AliceBundle\PhpUnit\ReloadDatabaseTrait;

final class SetupControllerTest extends ApiTestCase
{
    use ReloadDatabaseTrait;

    public function testIndex(): void
    {
        $client = self::createClient();
        $container = self::getContainer();

        $secret = $container->getParameter('install_password');
        $setupDTO = new SetupDTO(
            'admin@ketmie.com',
            'password',
            $secret
        );
        $client = static::createClient();
        $client->request('POST', '/setup', [
            'json' => $setupDTO,
            'headers' => [
                'Accept' => 'application/json',
                'Content-Type' => 'application/json'
            ]
        ]);

        self::assertResponseIsSuccessful();
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        self::$alwaysBootKernel = false;
    }
}
